---
- name: Install Docker on CentOS
  hosts: servervm1
  become: true
  tasks:
    - name: Add Docker repository
      command: dnf config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo

    - name: Install Docker packages
      dnf:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-compose-plugin
        state: present

    - name: Start Docker service
      systemd:
        name: docker
        state: started

    - name: Enable Docker service
      systemd:
        name: docker
        enabled: true

    - name: Check Docker service status
      command: systemctl status docker
      register: docker_status
      ignore_errors: yes

    - name: Print Docker service status
      debug:
        var: docker_status.stdout_lines

    - name: Install Maven
      dnf:
        name: maven
        state: present

    - name: Run Maven package
      command: mvn package
      args:
        chdir: /home/username/BankingMicroservice1/project1  # Replace with your actual project path
      when: ansible_facts.packages['maven'] is defined  # Ensure Maven is installed before running mvn package

    # Correct indentation for "Run Docker container"
    - name: Run Docker container
      docker_container:
        name: banking_microservice_container  # Replace with your desired container name
        image: banking_microservice:latest  # Reference the Docker image created earlier
        state: started
        restart_policy: always  # Automatically restart the container if it stops
        ports:
          - "8081:8080"  # Map host port 8081 to container port 8080 (adjust as needed)
